name: Auto Label PR Size

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  label-pr-size:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Calculate the number of changed files
        id: pr_size
        run: |
          # Get the number of files changed in the PR
          pr_size=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | wc -l)
          echo "PR size: $pr_size files"
          echo "pr_size=$pr_size" >> $GITHUB_ENV

      - name: Add size label
        id: pr_size_label
        run: |
            gh pr edit ${{ github.event.pull_request.number }} --add-label "bug"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
