name: Auto Label PR Size

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  label-pr-size:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2
        
      - name: Calculate lines of code changed
        id: lines_changed
        run: |
          # Get the diff stat between the base and head commit
          DIFF_STAT=$(git diff --shortstat ${{ github.event.before }} ${{ github.sha }})
          echo "Diff Stat: $DIFF_STAT"
          
          # Extract the number of lines added and removed
          #ADDED_LINES=$(echo "$DIFF_STAT" | grep -oP '\d+(?= insertions\(\+.*\))')
          #REMOVED_LINES=$(echo "$DIFF_STAT" | grep -oP '\d+(?= deletions\(-.*\))')
          
          # Handle cases where no lines were added or removed
          #ADDED_LINES=${ADDED_LINES:-0}
          #REMOVED_LINES=${REMOVED_LINES:-0}
          
          # Calculate total lines of code changed
          TOTAL_CHANGED=$DIFF_STAT
          #echo "Total Lines Changed: $TOTAL_CHANGED"
          
          # Output the total lines changed for use in other steps
          echo "lines_changed=$TOTAL_CHANGED" >> $GITHUB_ENV

      - name: Output lines changed
        run: |
          echo "Total lines changed in the PR: ${{ env.lines_changed }}"

      - name: Add size label
        id: pr_size_label
        run: |
          if [ ${{ env.pr_size }} -le 5 ]; then
           gh pr edit ${{ github.event.pull_request.number }} --add-label "Small"
          elif [ ${{ env.pr_size }} -le 20 ]; then
            gh pr edit ${{ github.event.pull_request.number }} --add-label "Medium"
          else
            gh pr edit ${{ github.event.pull_request.number }} --add-label "Large"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
